# Generated by Django 6.0.7 on 2026-07-24 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FabricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='جنس پارچه')),
            ],
        ),
        migrations.CreateModel(
            name='ClothRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_code', models.CharField(max_length=50, unique=True, verbose_name='کد طاقه')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('shade', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد شید / رنگ\u200cرزی')),
                ('length_meters', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='متراژ طاقه (متر)')),
                ('status', models.CharField(choices=[('IN_STOCK', 'موجود در انبار'), ('IN_CUTTING', 'در حال استفاده در برشگاه'), ('EXHAUSTED', 'تمام شده')], default='IN_STOCK', max_length=20, verbose_name='وضعیت طاقه')),
                ('supplier_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='تامین\u200cکننده / خریدار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ورود به انبار')),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolls', to='inventory.fabrictype', verbose_name='جنس پارچه')),
            ],
        ),
    ]
