# Generated by Django 6.0.7 on 2026-07-24 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cutting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SewingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(max_length=100, unique=True, verbose_name='کد کار خیاطی')),
                ('assigned_pieces', models.PositiveIntegerField(verbose_name='تعداد قطعات تحویلی')),
                ('completed_pieces', models.PositiveIntegerField(default=0, verbose_name='تعداد قطعات دوخته\u200cشده')),
                ('rejected_pieces', models.PositiveIntegerField(default=0, verbose_name='تعداد ضایعات / مرجوعی')),
                ('unit_sewing_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='اجرت دوخت هر واحد (تومان)')),
                ('status', models.CharField(choices=[('ASSIGNED', 'تخصیص یافته به خیاط'), ('IN_PROGRESS', 'در حال دوخت'), ('COMPLETED', 'تکمیل شده'), ('SETTLED', 'تسویه شده')], default='ASSIGNED', max_length=30, verbose_name='وضعیت دوخت')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تحویل به خیاط')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اتمام دوخت')),
                ('cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sewing_jobs', to='cutting.cut', verbose_name='دستور برش')),
            ],
        ),
    ]
