# Generated by Django 6.0.7 on 2026-07-24 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sewing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sewingjob',
            name='sewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sewing_assignments', to=settings.AUTH_USER_MODEL, verbose_name='خیاط / کارگاه خیاطی'),
        ),
    ]
