# Generated by Django 6.0.7 on 2026-07-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, verbose_name='نام دارنده حساب')),
                ('l_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('card_number', models.CharField(max_length=16, unique=True, verbose_name='شماره کارت (۱۶ رقمی)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=50, verbose_name='شماره پیگیری')),
                ('date_jalali', models.CharField(max_length=10, verbose_name='تاریخ شمسی (مثلا ۱۴۰۵/۰۵/۰۲)')),
                ('time_str', models.CharField(blank=True, max_length=5, null=True, verbose_name='زمان (HH:MM)')),
                ('atm_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره ترمینال')),
                ('recovery_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره بازیابی')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ (تومان)')),
                ('receipt_type', models.CharField(choices=[('CUTTING_PAYROLL', 'تسویه اجرت برشکاری'), ('SEWING_PAYROLL', 'تسویه اجرت خیاطی'), ('FABRIC_PURCHASE', 'خرید پارچه / مواد اولیه'), ('PRODUCER_PAYMENT', 'دریافتی از سفارش\u200cدهنده'), ('OTHER', 'سایر تراکنش\u200cها')], default='OTHER', max_length=30, verbose_name='نوع تراکنش')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار تایید'), ('VERIFIED', 'تایید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20, verbose_name='وضعیت فیش')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات و بابت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در سیستم')),
            ],
        ),
    ]
