# Generated by Django 6.0.7 on 2026-07-24 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مرتبط'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_receipts', to='financial.account', verbose_name='از حساب'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_receipts', to='financial.account', verbose_name='به حساب'),
        ),
    ]
