import {
  SquaresFour,
  ListChecks,
  ChatTeardropText,
  Users,
  ShieldCheck,
  Lock,
  Receipt,
  Gear,
  Question,
  UserGear,
  UserMinus,
  Command,
  Waveform,
  BoundingBox,
  HardHat,
  Desktop,
  Bug,
  FileX,
  Bell,
  Package,
  Palette,
  CloudSlash,
  Wrench,
  CaretRight,
  CaretUpDown,
  Sparkle,
  CreditCard,
  SignOut,
  SealCheck,
  Check,
  X,
  Plus,
  Trash,
  PencilSimple,
  MagnifyingGlass,
  Sun,
  Moon,
  Scissors,
  TShirt,
  CoatHanger,
  Dress,
  ShirtFolded,
  Scroll,
  Towel,
  Stack,
} from '@phosphor-icons/react'

// Export Phosphor icons with alias names matching standard icon names
// This creates a central abstraction layer for icons in the application.
export {
  // Navigation & Dashboard
  SquaresFour as LayoutDashboard,
  ListChecks as ListTodo,
  ChatTeardropText as MessagesSquare,
  Users,
  ShieldCheck,
  Lock,
  Receipt,
  UserMinus as UserX,
  Gear as Settings,
  Question as HelpCircle,
  UserGear as UserCog,
  Command,
  Waveform as AudioWaveform,
  BoundingBox as GalleryVerticalEnd,
  HardHat as Construction,
  Desktop as Monitor,
  Bug,
  FileX,
  Bell,
  Package,
  Palette,
  CloudSlash as ServerOff,
  Wrench,
  Scissors,
  
  // Financial & Inventory / Apparel
  CreditCard,
  TShirt,
  CoatHanger,
  Dress,
  ShirtFolded,
  Scroll,
  Towel,
  Stack,
  
  // UI Controls & Arrows
  CaretRight as ChevronRight,
  CaretUpDown as ChevronsUpDown,
  
  // User & Account Menu
  Sparkle as Sparkles,
  SignOut as LogOut,
  SealCheck as BadgeCheck,
  
  // Common Actions
  Check,
  X,
  Plus,
  Trash,
  PencilSimple as Edit,
  MagnifyingGlass as Search,
  Sun,
  Moon,
}
