# Generated by Django 6.0.7 on 2026-07-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('cut_code', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='کد دستور برش')),
                ('model_name', models.CharField(max_length=100, verbose_name='نام مدل')),
                ('model_code', models.CharField(max_length=100, verbose_name='کد مدل')),
                ('size', models.CharField(choices=[('FREE', 'Free Size'), ('TWO', 'سایز ۲'), ('THREE', 'سایز ۳'), ('FOUR', 'سایز ۴')], default='FREE', max_length=10, verbose_name='سایز بندی')),
                ('lai_per_unit', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد لا')),
                ('product_per_layer', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد قطعه در هر لا')),
                ('length_of_layers', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='متراژ لا (متر)')),
                ('cutting_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='اجرت برش (تومان)')),
                ('sewing_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='اجرت خیاطی (تومان)')),
                ('cutting_price_raw', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت تمام\u200cشده برش (تومان)')),
                ('sewing_price_raw', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت تمام\u200cشده خیاطی (تومان)')),
                ('status', models.CharField(choices=[('PLANNED', 'برنامه\u200cریزی اولیه'), ('IN_PROGRESS', 'در حال برش'), ('COMPLETED', 'برش تکمیل شده'), ('DELIVERED_TO_SEWING', 'تحویل به کارگاه خیاطی')], default='PLANNED', max_length=30, verbose_name='وضعیت برش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='CutRollUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_meters', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='متراژ مصرف شده')),
                ('used_layers', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد لا مصرفی')),
                ('produced_pieces', models.PositiveIntegerField(default=0, verbose_name='تعداد قطعات خروجی')),
            ],
        ),
    ]
