# Generated by Django 6.0.7 on 2026-07-24 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cutting', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='cutter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cut_jobs', to=settings.AUTH_USER_MODEL, verbose_name='برشکار'),
        ),
        migrations.AddField(
            model_name='cut',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cuts', to=settings.AUTH_USER_MODEL, verbose_name='تولیدکننده / سفارش\u200cدهنده'),
        ),
        migrations.AddField(
            model_name='cutrollusage',
            name='cut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_usages', to='cutting.cut', verbose_name='دستور برش'),
        ),
        migrations.AddField(
            model_name='cutrollusage',
            name='roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cut_usages', to='inventory.clothroll', verbose_name='طاقه پارچه'),
        ),
    ]
